# Generated by Django 2.2.8 on 2019-12-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('1', 'Convenience Goods'), ('2', 'Shopping Goods'), ('3', 'Specialty Goods')], max_length=125)),
                ('picture', models.ImageField(upload_to='project_name/media/products/images/')),
                ('amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production_date', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='project_name/media/products/files')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('detailed_view_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
